# Autogenerated wrapper script for VOLK_jll for x86_64-apple-darwin
export libvolk, list_cpu_features, volk_config_info, volk_profile

using boost_jll
JLLWrappers.@generate_wrapper_header("VOLK")
JLLWrappers.@declare_library_product(libvolk, "@rpath/libvolk.2.5.dylib")
JLLWrappers.@declare_executable_product(list_cpu_features)
JLLWrappers.@declare_executable_product(volk_config_info)
JLLWrappers.@declare_executable_product(volk_profile)
function __init__()
    JLLWrappers.@generate_init_header(boost_jll)
    JLLWrappers.@init_library_product(
        libvolk,
        "lib/libvolk.2.5.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        list_cpu_features,
        "bin/list_cpu_features",
    )

    JLLWrappers.@init_executable_product(
        volk_config_info,
        "bin/volk-config-info",
    )

    JLLWrappers.@init_executable_product(
        volk_profile,
        "bin/volk_profile",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
