# Autogenerated wrapper script for VOLK_jll for x86_64-w64-mingw32-cxx11
export libvolk, list_cpu_features, volk_config_info, volk_profile

using boost_jll
JLLWrappers.@generate_wrapper_header("VOLK")
JLLWrappers.@declare_library_product(libvolk, "libvolk.dll")
JLLWrappers.@declare_executable_product(list_cpu_features)
JLLWrappers.@declare_executable_product(volk_config_info)
JLLWrappers.@declare_executable_product(volk_profile)
function __init__()
    JLLWrappers.@generate_init_header(boost_jll)
    JLLWrappers.@init_library_product(
        libvolk,
        "bin\\libvolk.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        list_cpu_features,
        "bin\\list_cpu_features.exe",
    )

    JLLWrappers.@init_executable_product(
        volk_config_info,
        "bin\\volk-config-info.exe",
    )

    JLLWrappers.@init_executable_product(
        volk_profile,
        "bin\\volk_profile.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
